name: CI

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # - uses: denoland/setup-deno@v1
    #   with:
    #     deno-version: v1.x

    # - run: deno fmt --check
    - run: cargo fmt --check

    - run: cargo build --verbose
    - run: cargo test --verbose
    - run: cargo doc
